### ISSUE TITLE
Expose transactions?

### ISSUE THREAD

**Issue by zippoxer** [benbjohnson/wtf#10]
I've been thinking about this package layout, and I'm really admiring it thus far.

Web applications may issue a number of changes per request. For instance, a request to register a user may issue an insert a user record to *users* and (for whatever reason) a separate record to *user_registration_log". Over time, registration may get more complex and involve other changes to different tables/buckets in the database. In these cases, I believe it's safer (and a tiny bit faster) to bundle these database writes into a transaction and commit it at the end of the request handler or roll it back if the registration failed, so in no case you would have half-writes done. For instance if the server crashed between the insertion to *users* and *user_registration_log", without a transaction - there'd be a record in *users* but not in *user_registration_log*, thus we lose integrity.

I hope I made my point about why I believe transactions need to be handled at a higher level than the service (which would be *UserService* and *UserRegistrationLogService* given the example above).

I'm not asking to change anything in this repository, I'm just interested to hear what would be your approach to solve the problem I explained above - how would you expose transactions in this package layout so that request handlers can utilize them?

**Comment by benbjohnson** [comment]
@zippoxer Thanks, I'm glad you're liking the layout.

As for transactions, I would typically make a single function that performs both actions. For your example, I would probably have the `UserService.CreateUser()` simply add a `users` and `user_registration_logs` record within a `sql.Tx` inside the implementation.

A slightly more complicated (but common) example would be when someone signs up for an account on a web site and need to create a user at the same time. Since an `Account` always requires at least one `User` then I would make the `AccountService.CreateAccount()` require both objects:

```go
func (s *AccountService) CreateAccount(a *Account, u *User) error
```

I'm not a fan of exposing the actual `Tx` to the domain because I think it sets an expectation that all actions within the domain can be chained together transactionally. However, that's a strong guarantee to make across various implementations of your domain. e.g. if you have an HTTP implementation of your domain then you are likely not implementing distributed transactions across it. I think combining higher level transactional actions into a single function is much cleaner.

**Comment by zippoxer** [comment]
@benbjohnson Thanks for guiding me through your stance on this.

I agree with you about exposing `Tx`. I'm going to give up on transaction per request for now, since with this layout, it's going to cause a lot of duplicate code (a separate method for every request that does multiple writes). So, I will only write methods for transactions where they are needed logic-wise (say, for the rollback functionality).
